import { Inter } from "next/font/google";
import "./globals.css";
import NextUiProvider from "@/components/NextUiProvider";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        <NextUiProvider>
          <main className="dark:bg-dark bg-light min-h-[100vh] flex flex-col justify-between">
            <Nav />
            {children}
            <Footer />
          </main>
        </NextUiProvider>
      </body>
    </html>
  );
}
